config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :perfumes
  resources :users, only: [:show]
  resources :apples do
    resources :likes, only: [:create, :destroy]
  end
  root 'apples#index'
 
  

  
end

app/models/apple.rb
class Apple < ApplicationRecord
    belongs_to :user

    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :apple
  belongs_to :user

  validates_uniqueness_of :apple_id, scope: :user_id
end

app/models/perfume.rb
class Perfume < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :validatable
  
       has_many :likes, dependent: :destroy
       has_many :liked_apples, through: :likes, source: :apple
       has_many :apples, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }

  mount_uploader :image, ImageUploader
  def already_liked?(apple)
    self.likes.exists?(apple_id: apple.id)
  end
end

app/controllers/apples_controller.rb
class ApplesController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]  
    def index
        @apples = Apple.all
    end
    
    
    def new
        @apple = Apple.new
      end
    
      def create
        apple = Apple.new(apple_params)
        if apple.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @apple = Apple.find(params[:id])
      end




      def edit
        @apple = Apple.find(params[:id])
      end

      def update
        apple = Apple.find(params[:id])
        if apple.update(apple_params)
          redirect_to :action => "show", :id => apple.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        apple = Apple.find(params[:id])
        apple.destroy
        redirect_to action: :index
      end

      def create
        apple = Apple.new(apple_params)
    
        apple.user_id = current_user.id  #追記
    
        if apple.save
          redirect_to action: "index"
        else
          redirect_to action: "new"
        end
      end 

      private
      def apple_params
        params.require(:apple).permit(:name, :date, :adress, :about, :user_id, :image,:lat,:lng)
      end 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(apple_id: params[:apple_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(apple_id: params[:apple_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/perfumes_controller.rb
class PerfumesController < ApplicationController

        def index
        end
    
        def new
            @perfume = Perfume.new
        end
    
        def show
            @perfume = Perfume.find_by(id: params[:id])
        end
    
        def create
            perfume = Perfume.new(perfume_params)
            if perfume.save
                flash[:notice] = "診断が完了しました"
                redirect_to perfume_path(perfume.id)
            else
                redirect_to :action => "new"
            end
        end
      
      private
        def perfume_params
            params.require(:perfume).permit(:question1, :question2, :question3, :question4)
        end
 end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
      @user = User.find(params[:id]) 
    end
  end

app/helpers/apples_helper.rb
module ApplesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/perfumes_helper.rb
module PerfumesHelper
end

app/views/apples/edit.html.erb
<%= form_for @apple do |f| %>
    <%= f.label :about %>
    <%= f.text_field :about, :size => 140 %> 
    <%= f.submit "編集する" %>
  <% end %>

app/views/apples/index.html.erb
<%= link_to "診断へ", perfumes_path %>


<% if user_signed_in? %>
<%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>
<div class="apples-container">
  <% @apples.each do |t| %>
    <div class="apple">
      <%= t.name %>
      <%= t.about %>
      <%= t.adress %>
      <%= t.user.email %>

      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= link_to apple_like_path(id: t.id, apple_id: t.id), method: :delete do %>
            <i class="fas fa-heart"><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= link_to apple_likes_path(id: t.id, apple_id: t.id), method: :post do %>
            <i class="far fa-heart"></i> <%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <i class="far fa-heart"></i> <%= t.likes.count %>
  <% end %>
      <%= image_tag t.user.image_url, size: "250x200" if t.user.image? %>
     <%= link_to "詳細へ",apple_path(t.id) %> 

     <% if user_signed_in? && current_user.id == t.user_id %>
     <%= link_to "編集する", edit_apple_path(t.id) %>
     <%= link_to "削除する", apple_path(t.id), method: :delete %>
     <% end %> 
     </div>
     <div id='map'></div>

<style>
#map {
  height: 600px;
  width: 100%;
}
</style>

<!-- js部分 -->
<script>
    function initMap() {

      //初期表示位置
      let latlng = new google.maps.LatLng(38.60, 139.5);
      //デザイン
      let styles = [
           {
            stylers: [
             { "saturation": 0 },
             { "lightness": 0 }
            ]
           }
          ];

      let map = new google.maps.Map(document.getElementById('map'), {
          zoom: 5.5,
          styles: styles,
          center: latlng
      });
      let transitLayer = new google.maps.TransitLayer();
      transitLayer.setMap(map);

//複数マーカー ここから
      <% @apples.each do |apple|%>
        ( function() { 
          let markerLatLng = { lat: <%= apple.lat %>, lng: <%= apple.lng %> }; // 緯度経度のデータ作成
          let marker = new google.maps.Marker({ 
            position: markerLatLng, 
            map: map 
          });
//マーカーをクリックしたとき、詳細情報を表示
          let infowindow = new google.maps.InfoWindow({
            position: markerLatLng,
            content: "<a href='<%= apple_url(apple.id) %>' target='_blank'><%= apple.name %></a>"
          }); //ここで詳細ページへのリンクを表示させる
          marker.addListener('click', function() {
            infowindow.open(map, marker);
          });

       })();
      <% end %>
      //複数マーカー ここまで  
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBuZ_RfHNtJhwTppL5Bbi-l7tL7VrbOwbI&callback=initMap" async defer></script>



     <% end %>
   
  
</div>

app/views/apples/new.html.erb
<h1>新規投稿ページ</h1>

<%= form_for @apple do |f| %>

  <div class="field">
    <%= f.label :ユーザー名 %>
    <%= f.text_field :name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :旅行先  %>
    <%= f.select :adress, 
    [["北海道", "北海道"], 
    ["沖縄", "沖縄"], 
    ["東京", "東京"]], include_blank: "選択して下さい" %>
  </div>
 
  <div class="field">
    <%= f.label :感想  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>
  <div class="actions">
  
  <%= f.label :lat,"緯度" %>
  <%= f.text_field :lat,:value =>"緯度", id: :lat %>
  <%= f.label :lng,"経度" %>
  <%= f.text_field :lng,:value =>"経度", id: :lng %>
  <%= f.submit %>
</div>

<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API'] %>&callback=initMap" async defer></script>　


  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", apples_path %>

app/views/apples/show.html.erb
<h1>タイトル</h1>
<h3>Apple詳細</h3>
<div class="apple">
  <p><%= @apple.about %></p>
  <p><%= @apple.created_at %></p>

  <% if user_signed_in? %>
      <% if current_user.already_liked?(@apple) %>
        <%= link_to apple_like_path(@apple), method: :delete do %>
            <i class="fas fa-heart"><%= @apple.likes.count %>
        <% end %>
      <% else %>
        <%= link_to apple_likes_path(@apple), method: :post do %>
            <i class="far fa-heart"><%= @apple.likes.count %>
        <% end %>
      <% end %>
    <% else %>
    <i class="far fa-heart"><%= @apple.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_apple_path(@apple.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @apple.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "編集する", edit_apple_path(@apple.id) %>
<%= link_to "一覧に戻る", apples_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Travel</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/df13bbadbe.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

  <header>

  
  </header>
<main>
  
 
  <div class="hamburger-menu">
      <input type="checkbox" id="menu-btn-check">
      <label for="menu-btn-check" class="menu-btn"><span></span></label>
      <div class="menu-content">
      <ul>
      <% if user_signed_in? %>
       <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
      <% else %>
       <li><%= link_to "新規登録", new_user_registration_path %></li>
       <li><%= link_to "ログイン", new_user_session_path %></li>
      <% end %>
     <li><%= link_to "投稿", new_apple_path %></li>
      </ul>
    </div>
 </div>
  
   <%= yield %>
  </main>
 </body>
 
</html>

app/views/perfumes/index.html.erb
<div class="index-list">

   <div class="index-listb">
      <h2>Travel Japan</h2>
    </div>

    <div class="index-listd">
       <h1>旅行診断</h1>
   </div>


   <div class="index-listc">
      <%= link_to "診断を始める", new_perfume_path, class: "link" %>
   </div>

</div>

app/views/perfumes/new.html.erb
<%= form_for(@perfume, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="perfume-container">
        <div class="col-12">
            <p>Q1. あなたが好きな季節は？</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question1, "1", id: "custom_id1" %>
            <label for="custom_id1">春</label>
            <%= f.radio_button :question1, "2", id: "custom_id2" %>
            <label for="custom_id2">夏</label>
            <%= f.radio_button :question1, "3", id: "custom_id2" %>
            <label for="custom_id2">秋</label>
            <%= f.radio_button :question1, "4", id: "custom_id2" %>
            <label for="custom_id2">冬</label>
        </div>

        <div class="col-12">
            <p>Q2. どの地域に行きたいですか？</p>
        </div> 
        <div class="col-6">
            <%= f.radio_button :question2, "1", id: "custom_id3" %>
            <label for="custom_id3">北海道</label>
            <%= f.radio_button :question2, "2", id: "custom_id3" %>
            <label for="custom_id3">東北</label>
            <%= f.radio_button :question2, "3", id: "custom_id3" %>
            <label for="custom_id3">関東</label>
            <%= f.radio_button :question2, "4", id: "custom_id3" %>
            <label for="custom_id3">関西</label>
            <%= f.radio_button :question2, "5", id: "custom_id3" %>
            <label for="custom_id3">四国</label>
            <%= f.radio_button :question2, "6", id: "custom_id3" %>
            <label for="custom_id3">九州</label>
            <%= f.radio_button :question2, "7", id: "custom_id3" %>
            <label for="custom_id3">沖縄</label>
        </div>   
        <div class="col-12">
            <p>Q3. 人と接するときは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question3, "1", id: "custom_id5" %>
            <label for="custom_id5">相手の話をよく聞く方だ</label>
            <%= f.radio_button :question3, "2", id: "custom_id6" %>
            <label for="custom_id6">自分の話をよくする方だ</label>
        </div>
    
        <div class="col-12">
            <p>Q4. 大切にしたいのは…</p>
        </div>
        <div class="col-6">
            <%= f.radio_button :question4, "1", id: "custom_id7" %>
            <label for="custom_id7">論理性だ</label>
            <%= f.radio_button :question4, "2", id: "custom_id8" %>
            <label for="custom_id8">情緒だ</label>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit " 結果 " %>
    </div>
<% end %>

app/views/perfumes/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの香りは…</p>
</div>
<div class="perfume-container">
  <% case [@perfume.question1, @perfume.question2, @perfume.question3, @perfume.question4] %>
  <% when ["1", "1", "1", "1"] %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
  <% when ["1", "1", "1", "2"] %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>
  <% when ["1", "1", "2", "1"] %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>
  <% when ["1", "1", "2", "2"] %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>
  <% when ["1", "2", "1", "1"] %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>
  <% when ["1", "2", "1", "2"] %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>
  <% when ["1", "2", "2", "1"] %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>
  <% when ["1", "2", "2", "2"] %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
  <% when ["2", "1", "1", "1"] %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>
  <% when ["2", "1", "1", "2"] %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>
  <% when ["2", "1", "2", "1"] %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>
  <% when ["2", "1", "2", "2"] %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>
  <% when ["2", "2", "1", "1"] %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>
  <% when ["2", "2", "1", "2"] %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>
  <% when ["2", "2", "2", "1"] %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>
  <% when ["2", "2", "2", "2"] %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>
  <% end %>
</div>
<%= link_to "一覧に戻る", apples_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.apples.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
  <%= t.date %>
  <%= t.adress %>
  <%= t.about %>
<% end %>



<%= link_to "Tweet一覧に戻る", apples_path %>

<%= image_tag @user.image_url, size: "250x200" if @user.image? %>